/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#include <sstream>
#include <limits>
#include <map>
#include "ifcpp/reader/ReaderUtil.h"
#include "ifcpp/writer/WriterUtil.h"
#include "ifcpp/model/BasicTypes.h"
#include "ifcpp/model/BuildingException.h"
#include "ifcpp/IFC4X3/include/IfcAirTerminalBoxTypeEnum.h"

// TYPE IfcAirTerminalBoxTypeEnum = ENUMERATION OF	(CONSTANTFLOW	,VARIABLEFLOWPRESSUREDEPENDANT	,VARIABLEFLOWPRESSUREINDEPENDANT	,USERDEFINED	,NOTDEFINED);
void IFC4X3::IfcAirTerminalBoxTypeEnum::getStepParameter( std::stringstream& stream, bool is_select_type, size_t precision ) const
{
	if( is_select_type ) { stream << "IFCAIRTERMINALBOXTYPEENUM("; }
	switch( m_enum )
	{
		case ENUM_CONSTANTFLOW:	stream << ".CONSTANTFLOW."; break;
		case ENUM_VARIABLEFLOWPRESSUREDEPENDANT:	stream << ".VARIABLEFLOWPRESSUREDEPENDANT."; break;
		case ENUM_VARIABLEFLOWPRESSUREINDEPENDANT:	stream << ".VARIABLEFLOWPRESSUREINDEPENDANT."; break;
		case ENUM_USERDEFINED:	stream << ".USERDEFINED."; break;
		case ENUM_NOTDEFINED:	stream << ".NOTDEFINED."; break;
	}
	if( is_select_type ) { stream << ")"; }
}
shared_ptr<IFC4X3::IfcAirTerminalBoxTypeEnum> IFC4X3::IfcAirTerminalBoxTypeEnum::createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	if( arg.compare( "$" ) == 0 ) { return shared_ptr<IfcAirTerminalBoxTypeEnum>(); }
	if( arg.compare( "*" ) == 0 ) { return shared_ptr<IfcAirTerminalBoxTypeEnum>(); }
	shared_ptr<IfcAirTerminalBoxTypeEnum> type_object( new IfcAirTerminalBoxTypeEnum() );
	if( std_iequal( arg, ".CONSTANTFLOW." ) )
	{
		type_object->m_enum = IfcAirTerminalBoxTypeEnum::ENUM_CONSTANTFLOW;
	}
	else if( std_iequal( arg, ".VARIABLEFLOWPRESSUREDEPENDANT." ) )
	{
		type_object->m_enum = IfcAirTerminalBoxTypeEnum::ENUM_VARIABLEFLOWPRESSUREDEPENDANT;
	}
	else if( std_iequal( arg, ".VARIABLEFLOWPRESSUREINDEPENDANT." ) )
	{
		type_object->m_enum = IfcAirTerminalBoxTypeEnum::ENUM_VARIABLEFLOWPRESSUREINDEPENDANT;
	}
	else if( std_iequal( arg, ".USERDEFINED." ) )
	{
		type_object->m_enum = IfcAirTerminalBoxTypeEnum::ENUM_USERDEFINED;
	}
	else if( std_iequal( arg, ".NOTDEFINED." ) )
	{
		type_object->m_enum = IfcAirTerminalBoxTypeEnum::ENUM_NOTDEFINED;
	}
	return type_object;
}
