/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include "ifcpp/model/AttributeObject.h"
#include "ifcpp/model/BuildingException.h"
#include "ifcpp/model/BuildingGuid.h"
#include "ifcpp/reader/ReaderUtil.h"
#include "ifcpp/writer/WriterUtil.h"
#include "ifcpp/IFC4X3/include/IfcConnectionPointEccentricity.h"
#include "ifcpp/IFC4X3/include/IfcLengthMeasure.h"
#include "ifcpp/IFC4X3/include/IfcPointOrVertexPoint.h"

// ENTITY IfcConnectionPointEccentricity 
IFC4X3::IfcConnectionPointEccentricity::IfcConnectionPointEccentricity( int tag ) { m_tag = tag; }
void IFC4X3::IfcConnectionPointEccentricity::getStepLine( std::stringstream& stream, size_t precision ) const
{
	stream << "#" << m_tag << "= IFCCONNECTIONPOINTECCENTRICITY" << "(";
	if( m_PointOnRelatingElement ) { m_PointOnRelatingElement->getStepParameter( stream, true, precision ); } else { stream << "$" ; }
	stream << ",";
	if( m_PointOnRelatedElement ) { m_PointOnRelatedElement->getStepParameter( stream, true, precision ); } else { stream << "$" ; }
	stream << ",";
	if( m_EccentricityInX ) { m_EccentricityInX->getStepParameter( stream, false, precision ); } else { stream << "$"; }
	stream << ",";
	if( m_EccentricityInY ) { m_EccentricityInY->getStepParameter( stream, false, precision ); } else { stream << "$"; }
	stream << ",";
	if( m_EccentricityInZ ) { m_EccentricityInZ->getStepParameter( stream, false, precision ); } else { stream << "$"; }
	stream << ");";
}
void IFC4X3::IfcConnectionPointEccentricity::getStepParameter( std::stringstream& stream, bool /*is_select_type*/, size_t /*precision*/ ) const { stream << "#" << m_tag; }
void IFC4X3::IfcConnectionPointEccentricity::readStepArguments( const std::vector<std::string>& args, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	const size_t num_args = args.size();
	if( num_args > 0 ){m_PointOnRelatingElement = IfcPointOrVertexPoint::createObjectFromSTEP( args[0], map, errorStream );}
	if( num_args > 1 ){m_PointOnRelatedElement = IfcPointOrVertexPoint::createObjectFromSTEP( args[1], map, errorStream );}
	if( num_args > 2 ){m_EccentricityInX = IfcLengthMeasure::createObjectFromSTEP( args[2], map, errorStream );}
	if( num_args > 3 ){m_EccentricityInY = IfcLengthMeasure::createObjectFromSTEP( args[3], map, errorStream );}
	if( num_args > 4 ){m_EccentricityInZ = IfcLengthMeasure::createObjectFromSTEP( args[4], map, errorStream );}
	if( num_args != 5 ){ errorStream << "Wrong parameter count for entity IfcConnectionPointEccentricity, expecting 5, having " << num_args << ". Entity ID: " << m_tag << std::endl; }
}
void IFC4X3::IfcConnectionPointEccentricity::getAttributes( std::vector<std::pair<std::string, shared_ptr<BuildingObject> > >& vec_attributes ) const
{
	IFC4X3::IfcConnectionPointGeometry::getAttributes( vec_attributes );
	vec_attributes.emplace_back( std::make_pair( "EccentricityInX", m_EccentricityInX ) );
	vec_attributes.emplace_back( std::make_pair( "EccentricityInY", m_EccentricityInY ) );
	vec_attributes.emplace_back( std::make_pair( "EccentricityInZ", m_EccentricityInZ ) );
}
void IFC4X3::IfcConnectionPointEccentricity::getAttributesInverse( std::vector<std::pair<std::string, shared_ptr<BuildingObject> > >& vec_attributes_inverse ) const
{
	IFC4X3::IfcConnectionPointGeometry::getAttributesInverse( vec_attributes_inverse );
}
void IFC4X3::IfcConnectionPointEccentricity::setInverseCounterparts( shared_ptr<BuildingEntity> ptr_self_entity )
{
	IfcConnectionPointGeometry::setInverseCounterparts( ptr_self_entity );
}
void IFC4X3::IfcConnectionPointEccentricity::unlinkFromInverseCounterparts()
{
	IfcConnectionPointGeometry::unlinkFromInverseCounterparts();
}
