/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include "ifcpp/model/AttributeObject.h"
#include "ifcpp/model/BuildingException.h"
#include "ifcpp/model/BuildingGuid.h"
#include "ifcpp/reader/ReaderUtil.h"
#include "ifcpp/writer/WriterUtil.h"
#include "ifcpp/IFC4X3/include/IfcAxis2Placement.h"
#include "ifcpp/IFC4X3/include/IfcCosineSpiral.h"
#include "ifcpp/IFC4X3/include/IfcLengthMeasure.h"
#include "ifcpp/IFC4X3/include/IfcPresentationLayerAssignment.h"
#include "ifcpp/IFC4X3/include/IfcStyledItem.h"

// ENTITY IfcCosineSpiral 
IFC4X3::IfcCosineSpiral::IfcCosineSpiral( int tag ) { m_tag = tag; }
void IFC4X3::IfcCosineSpiral::getStepLine( std::stringstream& stream, size_t precision ) const
{
	stream << "#" << m_tag << "= IFCCOSINESPIRAL" << "(";
	if( m_Position ) { m_Position->getStepParameter( stream, true, precision ); } else { stream << "$" ; }
	stream << ",";
	if( m_CosineTerm ) { m_CosineTerm->getStepParameter( stream, false, precision ); } else { stream << "$"; }
	stream << ",";
	if( m_ConstantTerm ) { m_ConstantTerm->getStepParameter( stream, false, precision ); } else { stream << "$"; }
	stream << ");";
}
void IFC4X3::IfcCosineSpiral::getStepParameter( std::stringstream& stream, bool /*is_select_type*/, size_t /*precision*/ ) const { stream << "#" << m_tag; }
void IFC4X3::IfcCosineSpiral::readStepArguments( const std::vector<std::string>& args, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream )
{
	const size_t num_args = args.size();
	if( num_args > 0 ){m_Position = IfcAxis2Placement::createObjectFromSTEP( args[0], map, errorStream );}
	if( num_args > 1 ){m_CosineTerm = IfcLengthMeasure::createObjectFromSTEP( args[1], map, errorStream );}
	if( num_args > 2 ){m_ConstantTerm = IfcLengthMeasure::createObjectFromSTEP( args[2], map, errorStream );}
	if( num_args != 3 ){ errorStream << "Wrong parameter count for entity IfcCosineSpiral, expecting 3, having " << num_args << ". Entity ID: " << m_tag << std::endl; }
}
void IFC4X3::IfcCosineSpiral::getAttributes( std::vector<std::pair<std::string, shared_ptr<BuildingObject> > >& vec_attributes ) const
{
	IFC4X3::IfcSpiral::getAttributes( vec_attributes );
	vec_attributes.emplace_back( std::make_pair( "CosineTerm", m_CosineTerm ) );
	vec_attributes.emplace_back( std::make_pair( "ConstantTerm", m_ConstantTerm ) );
}
void IFC4X3::IfcCosineSpiral::getAttributesInverse( std::vector<std::pair<std::string, shared_ptr<BuildingObject> > >& vec_attributes_inverse ) const
{
	IFC4X3::IfcSpiral::getAttributesInverse( vec_attributes_inverse );
}
void IFC4X3::IfcCosineSpiral::setInverseCounterparts( shared_ptr<BuildingEntity> ptr_self_entity )
{
	IfcSpiral::setInverseCounterparts( ptr_self_entity );
}
void IFC4X3::IfcCosineSpiral::unlinkFromInverseCounterparts()
{
	IfcSpiral::unlinkFromInverseCounterparts();
}
