/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#pragma once
#include <vector>
#include <map>
#include <sstream>
#include <string>
#include "ifcpp/model/GlobalDefines.h"
#include "ifcpp/model/BasicTypes.h"
#include "ifcpp/model/BuildingObject.h"

namespace IFC4X3
{
	// TYPE IfcChimneyTypeEnum = ENUMERATION OF	(USERDEFINED	,NOTDEFINED);
	class IFCQUERY_EXPORT IfcChimneyTypeEnum : virtual public BuildingObject
	{
	public:
		enum IfcChimneyTypeEnumEnum
		{
			ENUM_USERDEFINED,
			ENUM_NOTDEFINED
		};

		IfcChimneyTypeEnum() = default;
		IfcChimneyTypeEnum( IfcChimneyTypeEnumEnum e ) { m_enum = e; }
		virtual uint32_t classID() const { return 627898853; }
		virtual void getStepParameter( std::stringstream& stream, bool is_select_type, size_t precision ) const;
		static shared_ptr<IfcChimneyTypeEnum> createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream );
		IfcChimneyTypeEnumEnum m_enum;
	};
}
