/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#pragma once
#include <vector>
#include <map>
#include <sstream>
#include <string>
#include "ifcpp/model/GlobalDefines.h"
#include "ifcpp/model/BasicTypes.h"
#include "ifcpp/model/BuildingObject.h"

namespace IFC4X3
{
	// TYPE IfcRailTypeEnum = ENUMERATION OF	(BLADE	,CHECKRAIL	,GUARDRAIL	,RACKRAIL	,RAIL	,STOCKRAIL	,USERDEFINED	,NOTDEFINED);
	class IFCQUERY_EXPORT IfcRailTypeEnum : virtual public BuildingObject
	{
	public:
		enum IfcRailTypeEnumEnum
		{
			ENUM_BLADE,
			ENUM_CHECKRAIL,
			ENUM_GUARDRAIL,
			ENUM_RACKRAIL,
			ENUM_RAIL,
			ENUM_STOCKRAIL,
			ENUM_USERDEFINED,
			ENUM_NOTDEFINED
		};

		IfcRailTypeEnum() = default;
		IfcRailTypeEnum( IfcRailTypeEnumEnum e ) { m_enum = e; }
		virtual uint32_t classID() const { return 2906317437; }
		virtual void getStepParameter( std::stringstream& stream, bool is_select_type, size_t precision ) const;
		static shared_ptr<IfcRailTypeEnum> createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream );
		IfcRailTypeEnumEnum m_enum;
	};
}
