/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#pragma once
#include <vector>
#include <map>
#include <sstream>
#include <string>
#include "ifcpp/model/GlobalDefines.h"
#include "ifcpp/model/BasicTypes.h"
#include "ifcpp/model/BuildingObject.h"
#include "IfcSimpleValue.h"

namespace IFC4X3
{
	// TYPE IfcTimeStamp = INTEGER;
	class IFCQUERY_EXPORT IfcTimeStamp : public IfcSimpleValue
	{
	public:
		IfcTimeStamp() = default;
		IfcTimeStamp( int value );
		virtual uint32_t classID() const { return 2591213694; }
		virtual void getStepParameter( std::stringstream& stream, bool is_select_type, size_t precision ) const;
		static shared_ptr<IfcTimeStamp> createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream );
		int m_value;
	};
}
