/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#pragma once
#include <vector>
#include <map>
#include <sstream>
#include <string>
#include "ifcpp/model/GlobalDefines.h"
#include "ifcpp/model/BasicTypes.h"
#include "ifcpp/model/BuildingObject.h"

namespace IFC4X3
{
	// TYPE IfcVibrationDamperTypeEnum = ENUMERATION OF	(AXIAL_YIELD	,BENDING_YIELD	,FRICTION	,RUBBER	,SHEAR_YIELD	,VISCOUS	,USERDEFINED	,NOTDEFINED);
	class IFCQUERY_EXPORT IfcVibrationDamperTypeEnum : virtual public BuildingObject
	{
	public:
		enum IfcVibrationDamperTypeEnumEnum
		{
			ENUM_AXIAL_YIELD,
			ENUM_BENDING_YIELD,
			ENUM_FRICTION,
			ENUM_RUBBER,
			ENUM_SHEAR_YIELD,
			ENUM_VISCOUS,
			ENUM_USERDEFINED,
			ENUM_NOTDEFINED
		};

		IfcVibrationDamperTypeEnum() = default;
		IfcVibrationDamperTypeEnum( IfcVibrationDamperTypeEnumEnum e ) { m_enum = e; }
		virtual uint32_t classID() const { return 1672225696; }
		virtual void getStepParameter( std::stringstream& stream, bool is_select_type, size_t precision ) const;
		static shared_ptr<IfcVibrationDamperTypeEnum> createObjectFromSTEP( const std::string& arg, const std::map<int,shared_ptr<BuildingEntity> >& map, std::stringstream& errorStream );
		IfcVibrationDamperTypeEnumEnum m_enum;
	};
}
