/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#include <sstream>
#include <limits>
#include <map>
#include "ifcpp/reader/ReaderUtil.h"
#include "ifcpp/writer/WriterUtil.h"
#include "ifcpp/model/IfcPPBasicTypes.h"
#include "ifcpp/model/IfcPPException.h"
#include "ifcpp/IFC4/include/IfcSegmentIndexSelect.h"
#include "ifcpp/IFC4/include/IfcArcIndex.h"

// TYPE IfcArcIndex = LIST [3:3] OF IfcPositiveInteger;
IfcArcIndex::IfcArcIndex() {}
IfcArcIndex::~IfcArcIndex() {}
shared_ptr<IfcPPObject> IfcArcIndex::getDeepCopy( IfcPPCopyOptions& options )
{
	shared_ptr<IfcArcIndex> copy_self( new IfcArcIndex() );
	copy_self->m_value = m_value;
	return copy_self;
}
void IfcArcIndex::getStepParameter( std::stringstream& stream, bool is_select_type ) const
{
	if( is_select_type ) { stream << "IFCARCINDEX("; }
	//TODO: implement
	if( is_select_type ) { stream << ")"; }
}
const std::wstring IfcArcIndex::toString() const
{
	std::wstringstream strs;
	strs << m_value;
	return strs.str();
}
shared_ptr<IfcArcIndex> IfcArcIndex::createObjectFromSTEP( const std::wstring& arg, const map_t<int,shared_ptr<IfcPPEntity> >& map )
{
	// read TYPE
	if( arg.compare( L"$" ) == 0 ) { return shared_ptr<IfcArcIndex>(); }
	else if( arg.compare( L"*" ) == 0 ) { return shared_ptr<IfcArcIndex>(); }
	shared_ptr<IfcArcIndex> type_object( new IfcArcIndex() );
	// read TYPE
	// read TYPE
	readInt( arg, type_object->m_value );
	return type_object;
}
