/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <sstream>
#include <limits>

#include "ifcpp/model/AttributeObject.h"
#include "ifcpp/model/BuildingException.h"
#include "ifcpp/model/BuildingGuid.h"
#include "ifcpp/reader/ReaderUtil.h"
#include "ifcpp/writer/WriterUtil.h"
#include "ifcpp/IFC4/include/IfcActorRole.h"
#include "ifcpp/IFC4/include/IfcAddress.h"
#include "ifcpp/IFC4/include/IfcIdentifier.h"
#include "ifcpp/IFC4/include/IfcLabel.h"
#include "ifcpp/IFC4/include/IfcOrganization.h"
#include "ifcpp/IFC4/include/IfcOrganizationRelationship.h"
#include "ifcpp/IFC4/include/IfcPersonAndOrganization.h"
#include "ifcpp/IFC4/include/IfcText.h"

// ENTITY IfcOrganization 
IfcOrganization::IfcOrganization() = default;
IfcOrganization::IfcOrganization( int id ) { m_entity_id = id; }
IfcOrganization::~IfcOrganization() = default;
shared_ptr<BuildingObject> IfcOrganization::getDeepCopy( BuildingCopyOptions& options )
{
	shared_ptr<IfcOrganization> copy_self( new IfcOrganization() );
	if( m_Identification ) { copy_self->m_Identification = dynamic_pointer_cast<IfcIdentifier>( m_Identification->getDeepCopy(options) ); }
	if( m_Name ) { copy_self->m_Name = dynamic_pointer_cast<IfcLabel>( m_Name->getDeepCopy(options) ); }
	if( m_Description ) { copy_self->m_Description = dynamic_pointer_cast<IfcText>( m_Description->getDeepCopy(options) ); }
	for(auto item_ii : m_Roles)
	{
			if( item_ii )
		{
			copy_self->m_Roles.push_back( dynamic_pointer_cast<IfcActorRole>(item_ii->getDeepCopy(options) ) );
		}
	}
	for(auto item_ii : m_Addresses)
	{
			if( item_ii )
		{
			copy_self->m_Addresses.push_back( dynamic_pointer_cast<IfcAddress>(item_ii->getDeepCopy(options) ) );
		}
	}
	return copy_self;
}
void IfcOrganization::getStepLine( std::stringstream& stream ) const
{
	stream << "#" << m_entity_id << "= IFCORGANIZATION" << "(";
	if( m_Identification ) { m_Identification->getStepParameter( stream ); } else { stream << "$"; }
	stream << ",";
	if( m_Name ) { m_Name->getStepParameter( stream ); } else { stream << "$"; }
	stream << ",";
	if( m_Description ) { m_Description->getStepParameter( stream ); } else { stream << "$"; }
	stream << ",";
	writeEntityList( stream, m_Roles );
	stream << ",";
	writeEntityList( stream, m_Addresses );
	stream << ");";
}
void IfcOrganization::getStepParameter( std::stringstream& stream, bool  /*is_select_type*/) const { stream << "#" << m_entity_id; }
const std::wstring IfcOrganization::toString() const { return L"IfcOrganization"; }
void IfcOrganization::readStepArguments( const std::vector<std::wstring>& args, const std::map<int,shared_ptr<BuildingEntity> >& map )
{
	const size_t num_args = args.size();
	if( num_args != 5 ){ std::stringstream err; err << "Wrong parameter count for entity IfcOrganization, expecting 5, having " << num_args << ". Entity ID: " << m_entity_id << std::endl; throw BuildingException( err.str() ); }
	m_Identification = IfcIdentifier::createObjectFromSTEP( args[0], map );
	m_Name = IfcLabel::createObjectFromSTEP( args[1], map );
	m_Description = IfcText::createObjectFromSTEP( args[2], map );
	readEntityReferenceList( args[3], m_Roles, map );
	readEntityReferenceList( args[4], m_Addresses, map );
}
void IfcOrganization::getAttributes( std::vector<std::pair<std::string, shared_ptr<BuildingObject> > >& vec_attributes ) const
{
	vec_attributes.emplace_back( "Identification", m_Identification );
	vec_attributes.emplace_back( "Name", m_Name );
	vec_attributes.emplace_back( "Description", m_Description );
	if( !m_Roles.empty() )
	{
		shared_ptr<AttributeObjectVector> Roles_vec_object( new AttributeObjectVector() );
		std::copy( m_Roles.begin(), m_Roles.end(), std::back_inserter( Roles_vec_object->m_vec ) );
		vec_attributes.emplace_back( "Roles", Roles_vec_object );
	}
	if( !m_Addresses.empty() )
	{
		shared_ptr<AttributeObjectVector> Addresses_vec_object( new AttributeObjectVector() );
		std::copy( m_Addresses.begin(), m_Addresses.end(), std::back_inserter( Addresses_vec_object->m_vec ) );
		vec_attributes.emplace_back( "Addresses", Addresses_vec_object );
	}
}
void IfcOrganization::getAttributesInverse( std::vector<std::pair<std::string, shared_ptr<BuildingObject> > >& vec_attributes_inverse ) const
{
	if( !m_IsRelatedBy_inverse.empty() )
	{
		shared_ptr<AttributeObjectVector> IsRelatedBy_inverse_vec_obj( new AttributeObjectVector() );
		for(const auto & i : m_IsRelatedBy_inverse)
		{
			if( !i.expired() )
			{
				IsRelatedBy_inverse_vec_obj->m_vec.push_back( shared_ptr<IfcOrganizationRelationship>( i ) );
			}
		}
		vec_attributes_inverse.emplace_back( "IsRelatedBy_inverse", IsRelatedBy_inverse_vec_obj );
	}
	if( !m_Relates_inverse.empty() )
	{
		shared_ptr<AttributeObjectVector> Relates_inverse_vec_obj( new AttributeObjectVector() );
		for(const auto & i : m_Relates_inverse)
		{
			if( !i.expired() )
			{
				Relates_inverse_vec_obj->m_vec.push_back( shared_ptr<IfcOrganizationRelationship>( i ) );
			}
		}
		vec_attributes_inverse.emplace_back( "Relates_inverse", Relates_inverse_vec_obj );
	}
	if( !m_Engages_inverse.empty() )
	{
		shared_ptr<AttributeObjectVector> Engages_inverse_vec_obj( new AttributeObjectVector() );
		for(const auto & i : m_Engages_inverse)
		{
			if( !i.expired() )
			{
				Engages_inverse_vec_obj->m_vec.push_back( shared_ptr<IfcPersonAndOrganization>( i ) );
			}
		}
		vec_attributes_inverse.emplace_back( "Engages_inverse", Engages_inverse_vec_obj );
	}
}
void IfcOrganization::setInverseCounterparts( shared_ptr<BuildingEntity> ptr_self_entity )
{
	shared_ptr<IfcOrganization> ptr_self = dynamic_pointer_cast<IfcOrganization>( ptr_self_entity );
	if( !ptr_self ) { throw BuildingException( "IfcOrganization::setInverseCounterparts: type mismatch" ); }
	for(auto & m_Addresse : m_Addresses)
	{
		if( m_Addresse )
		{
			m_Addresse->m_OfOrganization_inverse.push_back( ptr_self );
		}
	}
}
void IfcOrganization::unlinkFromInverseCounterparts()
{
	for(auto & m_Addresse : m_Addresses)
	{
		if( m_Addresse )
		{
			std::vector<weak_ptr<IfcOrganization> >& OfOrganization_inverse = m_Addresse->m_OfOrganization_inverse;
			for( auto it_OfOrganization_inverse = OfOrganization_inverse.begin(); it_OfOrganization_inverse != OfOrganization_inverse.end(); )
			{
				weak_ptr<IfcOrganization> self_candidate_weak = *it_OfOrganization_inverse;
				if( self_candidate_weak.expired() )
				{
					++it_OfOrganization_inverse;
					continue;
				}
				shared_ptr<IfcOrganization> self_candidate( *it_OfOrganization_inverse );
				if( self_candidate.get() == this )
				{
					it_OfOrganization_inverse= OfOrganization_inverse.erase( it_OfOrganization_inverse );
				}
				else
				{
					++it_OfOrganization_inverse;
				}
			}
		}
	}
}
