/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#include <sstream>
#include <limits>
#include <map>
#include "ifcpp/reader/ReaderUtil.h"
#include "ifcpp/writer/WriterUtil.h"
#include "ifcpp/model/BasicTypes.h"
#include "ifcpp/model/BuildingException.h"
#include "ifcpp/IFC4/include/IfcBendingParameterSelect.h"
#include "ifcpp/IFC4/include/IfcMeasureValue.h"
#include "ifcpp/IFC4/include/IfcPlaneAngleMeasure.h"

// TYPE IfcPlaneAngleMeasure = REAL;
IfcPlaneAngleMeasure::IfcPlaneAngleMeasure( double value ) { m_value = value; }
shared_ptr<BuildingObject> IfcPlaneAngleMeasure::getDeepCopy( BuildingCopyOptions& options )
{
	shared_ptr<IfcPlaneAngleMeasure> copy_self( new IfcPlaneAngleMeasure() );
	copy_self->m_value = m_value;
	return copy_self;
}
void IfcPlaneAngleMeasure::getStepParameter( std::stringstream& stream, bool is_select_type ) const
{
	if( is_select_type ) { stream << "IFCPLANEANGLEMEASURE("; }
	stream << m_value;
	if( is_select_type ) { stream << ")"; }
}
const std::wstring IfcPlaneAngleMeasure::toString() const
{
	std::wstringstream strs;
	strs << m_value;
	return strs.str();
}
shared_ptr<IfcPlaneAngleMeasure> IfcPlaneAngleMeasure::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<BuildingEntity> >& map )
{
	if( arg.compare( L"$" ) == 0 ) { return shared_ptr<IfcPlaneAngleMeasure>(); }
	if( arg.compare( L"*" ) == 0 ) { return shared_ptr<IfcPlaneAngleMeasure>(); }
	shared_ptr<IfcPlaneAngleMeasure> type_object( new IfcPlaneAngleMeasure() );
	readReal( arg, type_object->m_value );
	return type_object;
}
