/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#include <sstream>
#include <limits>
#include <map>
#include "ifcpp/reader/ReaderUtil.h"
#include "ifcpp/writer/WriterUtil.h"
#include "ifcpp/model/IfcPPBasicTypes.h"
#include "ifcpp/model/IfcPPException.h"
#include "ifcpp/IFC4/include/IfcMeasureValue.h"
#include "ifcpp/IFC4/include/IfcPositivePlaneAngleMeasure.h"

// TYPE IfcPositivePlaneAngleMeasure = IfcPlaneAngleMeasure;
IfcPositivePlaneAngleMeasure::IfcPositivePlaneAngleMeasure() {}
IfcPositivePlaneAngleMeasure::~IfcPositivePlaneAngleMeasure() {}
shared_ptr<IfcPPObject> IfcPositivePlaneAngleMeasure::getDeepCopy( IfcPPCopyOptions& options )
{
	shared_ptr<IfcPositivePlaneAngleMeasure> copy_self( new IfcPositivePlaneAngleMeasure() );
	copy_self->m_value = m_value;
	return copy_self;
}
void IfcPositivePlaneAngleMeasure::getStepParameter( std::stringstream& stream, bool is_select_type ) const
{
	if( is_select_type ) { stream << "IFCPOSITIVEPLANEANGLEMEASURE("; }
	stream << m_value;
	if( is_select_type ) { stream << ")"; }
}
const std::wstring IfcPositivePlaneAngleMeasure::toString() const
{
	std::wstringstream strs;
	strs << m_value;
	return strs.str();
}
shared_ptr<IfcPositivePlaneAngleMeasure> IfcPositivePlaneAngleMeasure::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.compare( L"$" ) == 0 ) { return shared_ptr<IfcPositivePlaneAngleMeasure>(); }
	else if( arg.compare( L"*" ) == 0 ) { return shared_ptr<IfcPositivePlaneAngleMeasure>(); }
	shared_ptr<IfcPositivePlaneAngleMeasure> type_object( new IfcPositivePlaneAngleMeasure() );
	readReal( arg, type_object->m_value );
	return type_object;
}
