/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "ifcpp/model/IfcPPBasicTypes.h"
#include "ifcpp/model/IfcPPException.h"
#include "ifcpp/reader/ReaderUtil.h"
#include "ifcpp/IFC4/include/IfcSpaceBoundarySelect.h"

// TYPE IfcSpaceBoundarySelect = SELECT	(IfcExternalSpatialElement	,IfcSpace);
shared_ptr<IfcSpaceBoundarySelect> IfcSpaceBoundarySelect::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.size() == 0 ){ return shared_ptr<IfcSpaceBoundarySelect>(); }
	if( arg.compare(L"$")==0 )
	{
		return shared_ptr<IfcSpaceBoundarySelect>();
	}
	if( arg.compare(L"*")==0 )
	{
		return shared_ptr<IfcSpaceBoundarySelect>();
	}
	shared_ptr<IfcSpaceBoundarySelect> result_object;
	readSelectType( arg, result_object, map );
	return result_object;
}
