/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#pragma once
#include <vector>
#include <map>
#include <sstream>
#include <string>
#include "ifcpp/model/IfcPPBasicTypes.h"
#include "ifcpp/model/IfcPPObject.h"
#include "ifcpp/model/IfcPPGlobal.h"

// TYPE IfcArithmeticOperatorEnum = ENUMERATION OF	(ADD	,DIVIDE	,MULTIPLY	,SUBTRACT);
class IFCPP_EXPORT IfcArithmeticOperatorEnum : virtual public IfcPPObject
{
public:
	enum IfcArithmeticOperatorEnumEnum
	{
		ENUM_ADD,
		ENUM_DIVIDE,
		ENUM_MULTIPLY,
		ENUM_SUBTRACT
	};

	IfcArithmeticOperatorEnum();
	IfcArithmeticOperatorEnum( IfcArithmeticOperatorEnumEnum e ) { m_enum = e; }
	~IfcArithmeticOperatorEnum();
	virtual const char* className() const { return "IfcArithmeticOperatorEnum"; }
	virtual shared_ptr<IfcPPObject> getDeepCopy( IfcPPCopyOptions& options );
	virtual void getStepParameter( std::stringstream& stream, bool is_select_type = false ) const;
	virtual const std::wstring toString() const;
	static shared_ptr<IfcArithmeticOperatorEnum> createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map );
	IfcArithmeticOperatorEnumEnum m_enum;
};

