/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#pragma once
#include <vector>
#include <map>
#include <sstream>
#include <string>
#include "ifcpp/model/GlobalDefines.h"
#include "ifcpp/model/BasicTypes.h"
#include "ifcpp/model/BuildingObject.h"

// TYPE IfcElectricFlowTreatmentDeviceTypeEnum = ENUMERATION OF	(ELECTRONICFILTER	,USERDEFINED	,NOTDEFINED);
class IFCQUERY_EXPORT IfcElectricFlowTreatmentDeviceTypeEnum : virtual public BuildingObject
{
public:
	enum IfcElectricFlowTreatmentDeviceTypeEnumEnum
	{
		ENUM_ELECTRONICFILTER,
		ENUM_USERDEFINED,
		ENUM_NOTDEFINED
	};

	IfcElectricFlowTreatmentDeviceTypeEnum() = default;
	IfcElectricFlowTreatmentDeviceTypeEnum( IfcElectricFlowTreatmentDeviceTypeEnumEnum e ) { m_enum = e; }
	~IfcElectricFlowTreatmentDeviceTypeEnum() = default;
	virtual const char* className() const { return "IfcElectricFlowTreatmentDeviceTypeEnum"; }
	virtual shared_ptr<BuildingObject> getDeepCopy( BuildingCopyOptions& options );
	virtual void getStepParameter( std::stringstream& stream, bool is_select_type = false ) const;
	virtual const std::wstring toString() const;
	static shared_ptr<IfcElectricFlowTreatmentDeviceTypeEnum> createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<BuildingEntity> >& map );
	IfcElectricFlowTreatmentDeviceTypeEnumEnum m_enum;
};

