/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#pragma once
#include <vector>
#include <map>
#include <sstream>
#include <string>
#include "ifcpp/model/IfcPPBasicTypes.h"
#include "ifcpp/model/IfcPPObject.h"
#include "ifcpp/model/IfcPPGlobal.h"

// TYPE IfcProtectiveDeviceTrippingUnitTypeEnum = ENUMERATION OF	(ELECTRONIC	,ELECTROMAGNETIC	,RESIDUALCURRENT	,THERMAL	,USERDEFINED	,NOTDEFINED);
class IFCPP_EXPORT IfcProtectiveDeviceTrippingUnitTypeEnum : virtual public IfcPPObject
{
public:
	enum IfcProtectiveDeviceTrippingUnitTypeEnumEnum
	{
		ENUM_ELECTRONIC,
		ENUM_ELECTROMAGNETIC,
		ENUM_RESIDUALCURRENT,
		ENUM_THERMAL,
		ENUM_USERDEFINED,
		ENUM_NOTDEFINED
	};

	IfcProtectiveDeviceTrippingUnitTypeEnum();
	IfcProtectiveDeviceTrippingUnitTypeEnum( IfcProtectiveDeviceTrippingUnitTypeEnumEnum e ) { m_enum = e; }
	~IfcProtectiveDeviceTrippingUnitTypeEnum();
	virtual const char* className() const { return "IfcProtectiveDeviceTrippingUnitTypeEnum"; }
	virtual shared_ptr<IfcPPObject> getDeepCopy( IfcPPCopyOptions& options );
	virtual void getStepParameter( std::stringstream& stream, bool is_select_type = false ) const;
	virtual const std::wstring toString() const;
	static shared_ptr<IfcProtectiveDeviceTrippingUnitTypeEnum> createObjectFromSTEP( const std::wstring& arg, const map_t<int,shared_ptr<IfcPPEntity> >& map );
	IfcProtectiveDeviceTrippingUnitTypeEnumEnum m_enum;
};

