/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#pragma once
#include <vector>
#include <map>
#include <sstream>
#include <string>
#include "ifcpp/model/GlobalDefines.h"
#include "ifcpp/model/BasicTypes.h"
#include "ifcpp/model/BuildingObject.h"

// TYPE IfcSpaceTypeEnum = ENUMERATION OF	(SPACE	,PARKING	,GFA	,INTERNAL	,EXTERNAL	,USERDEFINED	,NOTDEFINED);
class IFCQUERY_EXPORT IfcSpaceTypeEnum : virtual public BuildingObject
{
public:
	enum IfcSpaceTypeEnumEnum
	{
		ENUM_SPACE,
		ENUM_PARKING,
		ENUM_GFA,
		ENUM_INTERNAL,
		ENUM_EXTERNAL,
		ENUM_USERDEFINED,
		ENUM_NOTDEFINED
	};

	IfcSpaceTypeEnum() = default;
	IfcSpaceTypeEnum( IfcSpaceTypeEnumEnum e ) { m_enum = e; }
	virtual const char* className() const { return "IfcSpaceTypeEnum"; }
	virtual shared_ptr<BuildingObject> getDeepCopy( BuildingCopyOptions& options );
	virtual void getStepParameter( std::stringstream& stream, bool is_select_type = false ) const;
	virtual const std::wstring toString() const;
	static shared_ptr<IfcSpaceTypeEnum> createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<BuildingEntity> >& map );
	IfcSpaceTypeEnumEnum m_enum;
};

