/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#pragma once
#include <vector>
#include <map>
#include <sstream>
#include <string>
#include "ifcpp/model/IfcPPBasicTypes.h"
#include "ifcpp/model/IfcPPObject.h"
#include "ifcpp/model/IfcPPGlobal.h"
#include "IfcTextureCoordinate.h"
class IFCPP_EXPORT IfcLabel;
class IFCPP_EXPORT IfcReal;
//ENTITY
class IFCPP_EXPORT IfcTextureCoordinateGenerator : public IfcTextureCoordinate
{ 
public:
	IfcTextureCoordinateGenerator();
	IfcTextureCoordinateGenerator( int id );
	~IfcTextureCoordinateGenerator();
	virtual shared_ptr<IfcPPObject> getDeepCopy( IfcPPCopyOptions& options );
	virtual void getStepLine( std::stringstream& stream ) const;
	virtual void getStepParameter( std::stringstream& stream, bool is_select_type = false ) const;
	virtual void readStepArguments( const std::vector<std::wstring>& args, const map_t<int,shared_ptr<IfcPPEntity> >& map );
	virtual void setInverseCounterparts( shared_ptr<IfcPPEntity> ptr_self );
	virtual size_t getNumAttributes() { return 3; }
	virtual void getAttributes( std::vector<std::pair<std::string, shared_ptr<IfcPPObject> > >& vec_attributes );
	virtual void getAttributesInverse( std::vector<std::pair<std::string, shared_ptr<IfcPPObject> > >& vec_attributes );
	virtual void unlinkFromInverseCounterparts();
	virtual const char* className() const { return "IfcTextureCoordinateGenerator"; }


	// IfcPresentationItem -----------------------------------------------------------

	// IfcTextureCoordinate -----------------------------------------------------------
	// attributes:
	//  std::vector<shared_ptr<IfcSurfaceTexture> >	m_Maps;

	// IfcTextureCoordinateGenerator -----------------------------------------------------------
	// attributes:
	shared_ptr<IfcLabel>						m_Mode;
	std::vector<shared_ptr<IfcReal> >			m_Parameter;				//optional
};

